name = "db-site-worker"
type = "javascript"
account_id = "fa227777c8b69f6569d4a4347a6cceb8"
workers_dev = true
compatibility_date = "2022-04-01"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
[site]
bucket = "../../app"
entry-point = "./dist"
