name = "db-site-worker"
type = "webpack"
account_id = "fa227777c8b69f6569d4a4347a6cceb8"
workers_dev = true
webpack_config = "webpack.config.js"
kv_namespaces = []
compatibility_date = "2020-03-01"

[site]
bucket = "../../app"
entry-point = "./dist"
