name: Cloudflare Worker Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build sites
        run: bash netlify_build.sh
      - name: Install worker dependencies
        working-directory: 'packages/db-og-worker'
        run: npm ci
      - name: Publish to Cloudflare Worker
        working-directory: 'packages/db-og-worker'
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: npx wrangler publish
