name: Cloudflare Worker Publish

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
        matrix:
            node-version: [18]
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
            version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
            cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build sites
        run: bash netlify_build.sh
      - name: Install worker dependencies
        working-directory: "packages/db-og-worker"
        run: npm ci
      - name: Publish to Cloudflare Worker
        working-directory: "packages/db-og-worker"
        env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: npx wrangler publish